theme = "jetbrains_dark"

[editor]
true-color = true
line-number = "relative"
cursorline = true
cursorcolumn = true
mouse = false
bufferline = "multiple"
insert-final-newline = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.lsp]
enable = true
